name: BSPCompassTeleport
version: 1.1.3a
main: eu.blackspectrum.compassteleport.CompassTeleport
commands:
  compassteleportreload:
    description: Reloads the Compass Teleport config files.
    usage: /ctpreload
    permission: ctp.commands
    permission-message: You do not have permission to use this command.
    aliases: [compasstpreload, ctpreload]
permissions:
  ctp.commands:
    default: op